### ISSUE TITLE
adding gutenberg ids to Wikidata

### ISSUE THREAD

**Issue by maxlath** [gitenberg-dev/pg-wikipedia#1]
hi, thanks for this work!
Do you have plans and/or need help to add gutenberg ids to their respective Wikidata entity pages? There is a dedicated property for that: [P2034](https://www.wikidata.org/wiki/Property:P2034)

**Comment by eshellman** [comment]
I did not know about P2034. Was not planning to work on that, so go ahead.

Adding identifiers from Wikidata to our metadata is an obvious thing to do, but since I'm still working on deploying the metadata...

**Comment by maxlath** [comment]
just updated Wikidata with those ids!
Here is the updated [list of the Wikidata entities aware of their corresponding Gutenberg ebook id](https://github.com/maxlath/pg-wikipedia/blob/master/wd_entity_with_gutenberg_id.json)

**Comment by eshellman** [comment]
That's great, Max. Thanks!
